import os, sys

MYDIR = os.path.abspath(sys.path[0])

WIDTH, HEIGHT = 256, 256-24
MAP_HEIGHT = 176
HUD_HEIGHT = 56

SCALE = 3

BACKGROUND = "black"

PLAYER_SPEED = 6
PLAYER_SIZE = 15
PLAYER_HITBOX = (PLAYER_SIZE + 1) * SCALE

OCTOROC_SPEED = 6
OCTOROC_SIZE = 16
OCTOROC_HITBOX = (OCTOROC_SIZE + 1) * SCALE
