from enum import IntEnum

class State(IntEnum):
    IDLEIDLE = 11
    WALKIDLE = 12
    ATTACKIDLE = 13
    DAMAGEDIDLE = 14
    IDLEWALK = 21
    WALKWALK = 22
    ATTACKWALK = 23
    DAMAGEDWALK = 24
    IDLEATTACK = 31
    WALKATTACK = 32
    ATTACKATTACK = 33
    DAMAGEDATTACK = 34
    IDLEDAMAGED = 41
    WALKDAMAGED = 42
    ATTACKDAMAGED = 43
    DAMAGEDDAMAGED = 44